#pragma once

#include <cstdint>

enum ADCChannelType
{
    // Input PORT
    ADC_CHANNEL_TYPE_PORT_INPUT1_PIN1 = 0,
    ADC_CHANNEL_TYPE_PORT_INPUT2_PIN1,
    ADC_CHANNEL_TYPE_PORT_INPUT3_PIN1,
    ADC_CHANNEL_TYPE_PORT_INPUT4_PIN1,
    ADC_CHANNEL_TYPE_PORT_INPUT1_PIN6,
    ADC_CHANNEL_TYPE_PORT_INPUT2_PIN6,
    ADC_CHANNEL_TYPE_PORT_INPUT3_PIN6,
    ADC_CHANNEL_TYPE_PORT_INPUT4_PIN6,
    // Output PORT
    ADC_CHANNEL_TYPE_PORT_OUTPUT1_PIN5,
    ADC_CHANNEL_TYPE_PORT_OUTPUT2_PIN5,
    ADC_CHANNEL_TYPE_PORT_OUTPUT3_PIN5,
    ADC_CHANNEL_TYPE_PORT_OUTPUT4_PIN5,
    ADC_CHANNEL_TYPE_PORT_OUTPUT1_PIN6,
    ADC_CHANNEL_TYPE_PORT_OUTPUT2_PIN6,
    ADC_CHANNEL_TYPE_PORT_OUTPUT3_PIN6,
    ADC_CHANNEL_TYPE_PORT_OUTPUT4_PIN6,
    // System
    ADC_CHANNEL_TYPE_3V3_SENSE,
    ADC_CHANNEL_TYPE_5V_SENSE,
    ADC_CHANNEL_TYPE_9V_SENSE,

    ADC_CHANNEL_TOTAL
};

void hal_adc_init_default(uint8_t board_rev);